'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Elliteserv.StyleIcon.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Public ReadOnly Property I001() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I001", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I002() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I002", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I003() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I003", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I004() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I004", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I005() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I005", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I006() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I006", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I007() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I007", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I008() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I008", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I009() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I009", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I010() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I010", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I011() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I011", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I012() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I012", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I013() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I013", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I014() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I014", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I015() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I015", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I016() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I016", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I017() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I017", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I018() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I018", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I019() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I019", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I020() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I020", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I021() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I021", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I022() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I022", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I023() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I023", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I024() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I024", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I025() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I025", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I026() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I026", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I027() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I027", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I028() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I028", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I029() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I029", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I030() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I030", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I031() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I031", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I032() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I032", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I033() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I033", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I034() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I034", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property I035() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("I035", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
